name: Build

on:
  push:
    branches: [ 'main' ]

jobs: 
  matrix_build:
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: install system depedencies
        # install deps for windows, linux, and macos
        
      - name: Setup Rust
        uses: AtiltedTree/setup-rust@v1
        with:
          rust-version: stable

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependecies 
        run: npm install

      - name: Build
        run: npm run tauri build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: automata_${{ matrix.os }}
          path: /src-tauri/target/release/bundle
          retention-days: 7
