name: Build

on:
  push:
    branches: [ 'main', 'anthony', 'release-*' ]

jobs: 
  matrix_build:
    strategy:
      matrix:
        os: 
          - ubuntu-latest
            #- windows-latest
          #- macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        
      - name: install linux deps
        if: ${{ matrix.os }} == ubuntu-latest
        run: |
          sudo apt install -y \
            build-essential \
            libglib2.0-dev \
            libssl-dev \
            libgtk-3-dev \
            libappindicator3-dev \
            librsvg2-dev \
            libappindicator-dev \
            libgdk3.0-cil \
            libatk1.0-dev \
            libsoup2.4-dev 

      - name: Setup Rust
        uses: AtiltedTree/setup-rust@v1
        with:
          rust-version: stable

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependecies 
        run: npm install

      - name: Build
        run: npm run tauri build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: automata_${{ matrix.os }}
          path: /src-tauri/target/release/bundle
          retention-days: 7
